-- Service Provider Management Module Tables
USE cemetery_db;

SET NAMES utf8mb4;

-- Create service_provider table
CREATE TABLE IF NOT EXISTS `service_provider` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `provider_no` VARCHAR(50) NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `provider_name` VARCHAR(100) NOT NULL,
  `provider_type` TINYINT(1) NOT NULL DEFAULT 1,
  `business_license` VARCHAR(50) DEFAULT NULL,
  `legal_person` VARCHAR(50) DEFAULT NULL,
  `contact_person` VARCHAR(50) NOT NULL,
  `contact_phone` VARCHAR(20) NOT NULL,
  `contact_email` VARCHAR(100) DEFAULT NULL,
  `address` VARCHAR(200) DEFAULT NULL,
  `province` VARCHAR(50) DEFAULT NULL,
  `city` VARCHAR(50) DEFAULT NULL,
  `district` VARCHAR(50) DEFAULT NULL,
  `service_scope` VARCHAR(500) DEFAULT NULL,
  `business_hours` VARCHAR(100) DEFAULT NULL,
  `description` TEXT,
  `logo` VARCHAR(500) DEFAULT NULL,
  `images` TEXT,
  `certificate_images` TEXT,
  `rating` DECIMAL(3,2) DEFAULT 5.00,
  `service_count` INT(11) DEFAULT 0,
  `complaint_count` INT(11) DEFAULT 0,
  `status` TINYINT(1) DEFAULT 1,
  `audit_status` TINYINT(1) DEFAULT 1,
  `audit_time` DATETIME DEFAULT NULL,
  `audit_by` BIGINT(20) DEFAULT NULL,
  `audit_remark` VARCHAR(500) DEFAULT NULL,
  `join_date` DATE DEFAULT NULL,
  `contract_start_date` DATE DEFAULT NULL,
  `contract_end_date` DATE DEFAULT NULL,
  `is_recommended` TINYINT(1) DEFAULT 0,
  `sort_order` INT(11) DEFAULT 0,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `create_by` BIGINT(20) DEFAULT NULL,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_by` BIGINT(20) DEFAULT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  `remark` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_provider_no` (`provider_no`),
  KEY `idx_provider_name` (`provider_name`),
  KEY `idx_status` (`status`),
  KEY `idx_rating` (`rating` DESC)
) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create provider_service table
CREATE TABLE IF NOT EXISTS `provider_service` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `provider_id` BIGINT(20) NOT NULL,
  `service_no` VARCHAR(50) NOT NULL,
  `service_name` VARCHAR(100) NOT NULL,
  `service_category` TINYINT(1) NOT NULL DEFAULT 1,
  `service_type` TINYINT(1) DEFAULT 1,
  `price` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `original_price` DECIMAL(10,2) DEFAULT NULL,
  `price_unit` VARCHAR(20) DEFAULT 'times',
  `description` TEXT,
  `service_content` TEXT,
  `service_process` TEXT,
  `duration` INT(11) DEFAULT NULL,
  `cover_image` VARCHAR(500) DEFAULT NULL,
  `images` TEXT,
  `video_url` VARCHAR(500) DEFAULT NULL,
  `stock` INT(11) DEFAULT -1,
  `sales_count` INT(11) DEFAULT 0,
  `view_count` INT(11) DEFAULT 0,
  `rating` DECIMAL(3,2) DEFAULT 5.00,
  `review_count` INT(11) DEFAULT 0,
  `status` TINYINT(1) DEFAULT 1,
  `is_hot` TINYINT(1) DEFAULT 0,
  `is_new` TINYINT(1) DEFAULT 0,
  `is_recommended` TINYINT(1) DEFAULT 0,
  `sort_order` INT(11) DEFAULT 0,
  `publish_time` DATETIME DEFAULT NULL,
  `offline_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `create_by` BIGINT(20) DEFAULT NULL,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_by` BIGINT(20) DEFAULT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  `remark` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_service_no` (`service_no`),
  KEY `idx_provider_id` (`provider_id`, `status`),
  KEY `idx_service_name` (`service_name`)
) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create service_feedback table
CREATE TABLE IF NOT EXISTS `service_feedback` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `feedback_no` VARCHAR(50) NOT NULL,
  `order_id` BIGINT(20) NOT NULL,
  `provider_id` BIGINT(20) NOT NULL,
  `service_id` BIGINT(20) DEFAULT NULL,
  `user_id` BIGINT(20) NOT NULL,
  `feedback_type` TINYINT(1) DEFAULT 1,
  `rating` DECIMAL(3,2) NOT NULL DEFAULT 5.00,
  `service_rating` DECIMAL(3,2) DEFAULT NULL,
  `quality_rating` DECIMAL(3,2) DEFAULT NULL,
  `speed_rating` DECIMAL(3,2) DEFAULT NULL,
  `content` TEXT NOT NULL,
  `images` TEXT,
  `is_anonymous` TINYINT(1) DEFAULT 0,
  `is_top` TINYINT(1) DEFAULT 0,
  `like_count` INT(11) DEFAULT 0,
  `reply_content` TEXT,
  `reply_time` DATETIME DEFAULT NULL,
  `reply_by` BIGINT(20) DEFAULT NULL,
  `status` TINYINT(1) DEFAULT 1,
  `audit_status` TINYINT(1) DEFAULT 1,
  `audit_time` DATETIME DEFAULT NULL,
  `audit_by` BIGINT(20) DEFAULT NULL,
  `audit_remark` VARCHAR(500) DEFAULT NULL,
  `handle_time` DATETIME DEFAULT NULL,
  `handle_by` BIGINT(20) DEFAULT NULL,
  `handle_result` VARCHAR(500) DEFAULT NULL,
  `feedback_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `create_by` BIGINT(20) DEFAULT NULL,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_by` BIGINT(20) DEFAULT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  `remark` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_feedback_no` (`feedback_no`),
  KEY `idx_provider_id` (`provider_id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SELECT 'Tables created successfully!' AS status;
